name: data_lit_project
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.4.0
  - anyio=4.2.0
  - appnope=0.1.3
  - argon2-cffi=23.1.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - asttokens=2.4.1
  - async-lru=2.0.4
  - attrs=23.1.0
  - azure-core-cpp=1.10.3
  - azure-storage-blobs-cpp=12.10.0
  - azure-storage-common-cpp=12.5.0
  - babel=2.14.0
  - beautifulsoup4=4.12.2
  - bleach=6.1.0
  - blosc=1.21.5
  - branca=0.7.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.24.0
  - ca-certificates=2023.11.17
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2023.11.17
  - cffi=1.16.0
  - cfitsio=4.3.1
  - charset-normalizer=3.3.2
  - click=8.1.7
  - click-plugins=1.1.1
  - cligj=0.7.2
  - comm=0.1.4
  - contextily=1.5.0
  - contourpy=1.2.0
  - cycler=0.12.1
  - debugpy=1.8.0
  - decorator=5.1.1
  - defusedxml=0.7.1
  - entrypoints=0.4
  - et_xmlfile=1.1.0
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - filelock=3.13.1
  - fiona=1.9.5
  - folium=0.15.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.47.0
  - fqdn=1.5.1
  - freetype=2.12.1
  - freexl=2.0.0
  - fsspec=2023.12.2
  - gdal=3.8.2
  - geographiclib=1.52
  - geopandas=0.14.1
  - geopandas-base=0.14.1
  - geopy=2.4.1
  - geos=3.12.1
  - geotiff=1.7.1
  - gettext=0.21.1
  - giflib=5.2.1
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=73.2
  - idna=3.6
  - importlib-metadata=7.0.0
  - importlib_metadata=7.0.0
  - importlib_resources=6.1.1
  - ipykernel=6.26.0
  - ipython=8.18.1
  - ipywidgets=8.1.1
  - isoduration=20.11.0
  - jedi=0.19.1
  - jinja2=3.1.2
  - joblib=1.3.2
  - json-c=0.17
  - json5=0.9.14
  - jsonpointer=2.4
  - jsonschema=4.20.0
  - jsonschema-specifications=2023.11.2
  - jsonschema-with-format-nongpl=4.20.0
  - jupyter=1.0.0
  - jupyter-lsp=2.2.1
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.5.1
  - jupyter_events=0.9.0
  - jupyter_server=2.12.1
  - jupyter_server_terminals=0.5.0
  - jupyterlab=4.0.9
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.25.2
  - jupyterlab_widgets=3.0.9
  - kealib=1.5.3
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20230802.1
  - libaec=1.1.2
  - libarchive=3.7.2
  - libblas=3.9.0
  - libboost-headers=1.84.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcurl=8.5.0
  - libdeflate=1.19
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgdal=3.8.2
  - libgfortran5=13.2.0
  - libglib=2.78.3
  - libgoogle-cloud=2.12.0
  - libgrpc=1.59.3
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - libkml=1.3.0
  - liblapack=3.9.0
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libopenblas=0.3.25
  - libpng=1.6.39
  - libpq=16.1
  - libprotobuf=4.24.4
  - libre2-11=2023.06.02
  - librttopo=1.1.0
  - libsodium=1.0.18
  - libspatialindex=1.9.3
  - libspatialite=5.1.0
  - libsqlite=3.44.2
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxml2=2.12.3
  - libzip=1.10.1
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - lz4-c=1.9.4
  - lzo=2.10
  - mapclassify=2.6.1
  - markupsafe=2.1.3
  - matplotlib=3.8.2
  - matplotlib-base=3.8.2
  - matplotlib-inline=0.1.6
  - mercantile=1.2.1
  - minizip=4.0.3
  - mistune=3.0.2
  - mpmath=1.3.0
  - munkres=1.1.4
  - nbclient=0.8.0
  - nbconvert=7.13.0
  - nbconvert-core=7.13.0
  - nbconvert-pandoc=7.13.0
  - nbformat=5.9.2
  - nest-asyncio=1.5.8
  - networkx=3.2.1
  - nomkl=1.0
  - notebook=7.0.6
  - notebook-shim=0.2.3
  - numpy=1.26.2
  - openjpeg=2.5.0
  - openpyxl=3.0.10
  - openssl=3.2.0
  - overrides=7.4.0
  - packaging=23.2
  - pandas=2.1.4
  - pandoc=3.1.3
  - pandocfilters=1.5.0
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.1.0
  - pip=23.3.2
  - pixman=0.42.2
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.1.0
  - poppler=23.12.0
  - poppler-data=0.4.12
  - postgresql=16.1
  - proj=9.3.1
  - prometheus_client=0.19.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - psutil=5.9.7
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.17.2
  - pyparsing=3.1.1
  - pyproj=3.6.1
  - pysocks=1.7.1
  - python=3.12.0
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.19.0
  - python-json-logger=2.0.7
  - python-tzdata=2023.3
  - python_abi=3.12
  - pytorch=2.1.0
  - pytz=2023.3.post1
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qtconsole-base=5.5.1
  - qtpy=2.4.1
  - rasterio=1.3.9
  - re2=2023.06.02
  - referencing=0.32.0
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.15.2
  - rtree=1.1.0
  - scikit-learn=1.3.2
  - scipy=1.11.4
  - send2trash=1.8.2
  - setuptools=68.2.2
  - shapely=2.0.2
  - six=1.16.0
  - sleef=3.5.1
  - snappy=1.1.10
  - sniffio=1.3.0
  - snuggs=1.4.7
  - soupsieve=2.5
  - sqlite=3.44.2
  - stack_data=0.6.2
  - sympy=1.12
  - terminado=0.18.0
  - threadpoolctl=3.2.0
  - tiledb=2.18.3
  - tinycss2=1.2.1
  - tk=8.6.13
  - tomli=2.0.1
  - tornado=6.3.3
  - traitlets=5.14.0
  - types-python-dateutil=2.8.19.14
  - typing-extensions=4.9.0
  - typing_extensions=4.9.0
  - typing_utils=0.1.0
  - tzdata=2023c
  - uri-template=1.3.0
  - uriparser=0.9.7
  - urllib3=2.1.0
  - wcwidth=0.2.12
  - webcolors=1.13
  - webencodings=0.5.1
  - websocket-client=1.7.0
  - wheel=0.42.0
  - widgetsnbextension=4.0.9
  - xerces-c=3.2.5
  - xlrd=2.0.1
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xyzservices=2023.10.1
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
    - tueplots==0.0.12
    - nss=3.96
    - pyobjc-core=10.1
    - tzcode=2023c
    - readline=8.2
    - libcxx=16.0.6
    - pyobjc-framework-cocoa=10.1
    - libuv=1.46.0
    - libgfortran=5.0.0
    - ncurses=6.4
    - libedit=3.1.20191231
    - nspr=4.35
    - libev=4.33

